//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mowlds.github.io.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverResult
    {
        public int ID { get; set; }
        public int Driver { get; set; }
        public int Race { get; set; }
        public int SessionType { get; set; }
        public int FinalPosition { get; set; }
        public Nullable<int> RacePoints { get; set; }
        public string Time { get; set; }
        public string Delta { get; set; }
        public string BestLap { get; set; }
        public bool HasGridPenalty { get; set; }
        public Nullable<int> GridPenaltyDrop { get; set; }
        public bool HasTimePenalty { get; set; }
        public Nullable<int> TimePenaltyDuration { get; set; }
        public bool HasFastestLap { get; set; }
        public bool HasDriverOfTheDay { get; set; }
        public bool HasDNF { get; set; }
        public bool IsClassified { get; set; }
        public bool HasDSQ { get; set; }
        public bool HasGridBan { get; set; }
        public string Tyre1 { get; set; }
        public string Tyre2 { get; set; }
        public string Tyre3 { get; set; }
        public string Tyre4 { get; set; }
        public string Tyre5 { get; set; }
        public string Tyre6 { get; set; }
        public string Tyre7 { get; set; }
        public string Tyre8 { get; set; }
    
        public virtual Driver Driver1 { get; set; }
        public virtual Race Race1 { get; set; }
        public virtual Session Session { get; set; }
    }
}
