//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mowlds.github.io.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverTeam
    {
        public int Driver { get; set; }
        public Nullable<int> Team { get; set; }
        public int Season { get; set; }
    
        public virtual Driver Driver1 { get; set; }
        public virtual Season Season1 { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
