//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mowlds.github.io.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.DriverTeam = new HashSet<DriverTeam>();
            this.DriverResult = new HashSet<DriverResult>();
            this.RaceLaps = new HashSet<RaceLaps>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string ForumName { get; set; }
        public string PSNName { get; set; }
        public Nullable<int> DriverNumber { get; set; }
        public string Colour { get; set; }
        public string Fontstroke { get; set; }
        public string Bio { get; set; }
        public string DriverQuote { get; set; }
        public string DriverImage { get; set; }
        public string TwitchName { get; set; }
        public string KnownFor { get; set; }
        public Nullable<int> Pace { get; set; }
        public Nullable<int> Strategy { get; set; }
        public Nullable<int> Luck { get; set; }
        public Nullable<int> Snakeyness { get; set; }
        public Nullable<int> Chat { get; set; }
        public Nullable<int> Headsgone { get; set; }
        public Nullable<int> BoxOffice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverTeam> DriverTeam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverResult> DriverResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceLaps> RaceLaps { get; set; }
    }
}
