//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mowlds.github.io.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceLaps
    {
        public int ID { get; set; }
        public Nullable<int> Race { get; set; }
        public Nullable<int> SessionType { get; set; }
        public int Lap { get; set; }
        public Nullable<int> EventType { get; set; }
        public int LeadDriver { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Event Event { get; set; }
        public virtual Race Race1 { get; set; }
    }
}
