//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mowlds.github.io.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SRLContext1 : DbContext
    {
        public SRLContext1()
            : base("name=SRLContext1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<DriverResult> DriverResult { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Race> Race { get; set; }
        public virtual DbSet<RaceLaps> RaceLaps { get; set; }
        public virtual DbSet<Season> Season { get; set; }
        public virtual DbSet<Session> Session { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Track> Track { get; set; }
        public virtual DbSet<DriverTeam> DriverTeam { get; set; }
    }
}
